### ISSUE TITLE
server gui crashes immeadley

### ISSUE THREAD

**Issue by tylerhoot** [RappsFF7/Terraria-Server-GUI#1]
the server program exe will crash immeadly after you try to run the program

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	TerrariaServerCSGUI.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	57f8be08
  Problem Signature 04:	TerrariaServerCS
  Problem Signature 05:	1.0.0.0
  Problem Signature 06:	57e83d17
  Problem Signature 07:	5c
  Problem Signature 08:	1b
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.3.9600.2.0.0.144.8
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	6ee2
  Additional Information 4:	6ee2432e64e99bdcea5e4be767a3b1a2

**Comment by RappsFF7** [comment]
Thanks for the problem signature, that helps tremendously.

It looks like you're using Windows 8.1 (or Windows server 2012 R2). The last version was only tested on Windows 10, I'll get a VM up and running to see if Windows 8.1 has trouble... Though, "Null reference exception" listed there would suggest a code error on my part. You should also run it as an administrator if you have UAC enabled as UAC will block file access. If UAC is the issue, I'll have it forcibly run with admin rights in the next release.

**Comment by tylerhoot** [comment]
It was windows server 2012 R2 and I did try running it as a admin still crashed immediately

**Comment by RappsFF7** [comment]
I've added a new release 1.5.1. Go ahead and try that one, and let me know if you're still having problems.
